package com.gastos.storage

import androidx.room.withTransaction
import com.gastos.domain.model.*
import com.gastos.data.local.entity.*
import com.gastos.local.database.AppDatabase
import com.gastos.repository.ExchangeRateProvider
import kotlinx.coroutines.flow.*
import kotlinx.serialization.encodeToString
import java.util.*
import java.text.SimpleDateFormat
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class MonthlyLimitStore @Inject constructor(private val database: AppDatabase, private val rates: ExchangeRateProvider) {
    val limits = database.automationDao().observeLimits().map { rows -> rows.map { AutomationCodec.json.decodeFromString<MonthlyLimit>(it.payload) } }
    suspend fun put(limit: MonthlyLimit) = database.withTransaction {
        validate(limit)
        val identity = "${limit.categoryId}:${limit.month}"
        val previous = database.automationDao().limits().firstOrNull { it.id == identity }?.let { AutomationCodec.json.decodeFromString<MonthlyLimit>(it.payload) }
        write(limit.copy(id = identity, notified = previous?.notified == true))
    }
    suspend fun create(limit: MonthlyLimit) = database.withTransaction {
        validate(limit)
        val identity = "${limit.categoryId}:${limit.month}"
        require(database.automationDao().limits().none { it.id == identity }) { "LIMIT_ALREADY_EXISTS" }
        write(limit.copy(id = identity, notified = false))
    }
    /** Moving a limit never overwrites another destination and deletes the original atomically. */
    suspend fun update(originalId: String, limit: MonthlyLimit) = database.withTransaction {
        validate(limit)
        val all = database.automationDao().limits()
        val previous = all.firstOrNull { it.id == originalId } ?: error("RECORD_CHANGED")
        val identity = "${limit.categoryId}:${limit.month}"
        require(identity == originalId || all.none { it.id == identity }) { "LIMIT_ALREADY_EXISTS" }
        val old: MonthlyLimit = AutomationCodec.json.decodeFromString(previous.payload)
        write(limit.copy(id = identity, notified = identity == originalId && old.notified))
        if (identity != originalId) delete(originalId)
    }
    private suspend fun validate(limit: MonthlyLimit) {
        require(limit.amount.isFinite() && limit.amount > 0 && validMonth(limit.month)) { "LIMIT_INVALID" }
        require(runCatching { Currency.getInstance(limit.currency) }.isSuccess) { "CURRENCY_INVALID" }
        require(database.automationDao().categories().any { it.id == limit.categoryId && it.kind == "EXPENSE" && it.parentId.isEmpty() && !it.archived }) { "CATEGORY_INVALID" }
    }
    private suspend fun write(limit: MonthlyLimit) {
        database.automationDao().putLimit(MonthlyLimitEntity(limit.id, limit.categoryId, limit.month, AutomationCodec.json.encodeToString(limit)))
        database.automationDao().deleteRecord("limit:skip:${limit.id}")
    }
    suspend fun delete(id: String) = database.withTransaction {
        // Keep explicit removals/moves from being immediately regenerated by a previous repeating month.
        database.automationDao().putRecord(AutomationRecordEntity("limit:skip:$id", "LIMIT_SKIP", id))
        database.automationDao().deleteLimit(id)
    }
    private suspend fun repeatForMonth(categoryId: String, month: String): MonthlyLimit? = database.withTransaction {
        val id = "$categoryId:$month"
        val all = database.automationDao().limits().map { AutomationCodec.json.decodeFromString<MonthlyLimit>(it.payload) }
        val existing = all.firstOrNull { it.id == id }
        if (existing != null) return@withTransaction existing
        if (database.automationDao().record("limit:skip:$id") != null) return@withTransaction null
        val latest = all.filter { it.categoryId == categoryId && it.month < month }.maxByOrNull { it.month }
        if (latest == null || !latest.repeat || database.automationDao().categories().none { it.id == categoryId && !it.archived }) return@withTransaction null
        latest.copy(id = id, month = month, notified = false).also { write(it) }
    }
    fun progress(month: String): Flow<List<MonthlyLimitProgress>> = combine(limits, database.invoiceDao().getAllInvoices(), database.automationDao().observeCategories(), rates.rates) { saved, invoices, categories, _ ->
        val current = saved.filter { it.month == month }.toMutableList()
        saved.filter { it.repeat && it.month < month }.groupBy { it.categoryId }.forEach { (categoryId, _) ->
            if (current.none { it.categoryId == categoryId }) {
                repeatForMonth(categoryId, month)?.let(current::add)
            }
        }
        val start = requireNotNull(SimpleDateFormat("yyyy-MM-dd", Locale.ROOT).apply { isLenient = false }.parse("$month-01"))
        val end = Calendar.getInstance().apply { time = start; add(Calendar.MONTH, 1) }.timeInMillis
        current.map { MonthlyLimitCalculator.summarize(it, categories.firstOrNull { category -> category.id == it.categoryId }?.name.orEmpty(), invoices.map(InvoiceEntity::toDomain), start.time, end, rates::convert) }
    }
    suspend fun markNotified(limit: MonthlyLimit) {
        val existing = database.automationDao().limits().firstOrNull { it.id == limit.id } ?: return
        val current: MonthlyLimit = AutomationCodec.json.decodeFromString(existing.payload)
        if (current == limit) database.automationDao().putLimit(existing.copy(payload = AutomationCodec.json.encodeToString(current.copy(notified = true))))
    }
    companion object {
        fun currentMonth(): String = SimpleDateFormat("yyyy-MM", Locale.ROOT).format(Date())
        fun validMonth(value: String): Boolean = Regex("[0-9]{4}-(0[1-9]|1[0-2])").matches(value) && value.take(4).toInt() in 1900..9999
    }
}
